# Generated by Django 3.2.2 on 2021-05-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='total',
        ),
    ]
