# Generated by Django 3.2.2 on 2021-05-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
