# Generated by Django 3.2.2 on 2021-05-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
    ]
